apiVersion: v2
name: memobuild
description: A Helm chart for MemoBuild distributed build cache
type: application
version: 0.1.0
appVersion: "0.4.1"
kubeVersion: ">=1.24.0"
keywords:
  - memobuild
  - build-cache
  - distributed
  - oci
home: https://github.com/nrelab/MemoBuild
sources:
  - https://github.com/nrelab/MemoBuild
maintainers:
  - name: NRELabs
    email: hello@nrelab.io
annotations:
  category: DeveloperTools